/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.geektrust;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

@DisplayName("App Test")
class AppTest {
    private String fileLocation;
    private String[] input;
    private final PrintStream standardOut = System.out;
    private final ByteArrayOutputStream outputStream = new ByteArrayOutputStream();

    // @BeforeEach
    // public void setUp() {
    //     System.setOut(new PrintStream(outputStream,true));
    // }
    @Test
    @DisplayName("Test 1")
    public void integrationTest1(){
        // fileLocation = "./sample_input/input1.txt";
        // input = new String[]{fileLocation};
        // App.main(input);
        // String expected = "RENEWAL_REMINDER MUSIC 04-08-2024\n" +
        //         "RENEWAL_REMINDER VIDEO 04-10-2024\n" +
        //         "RENEWAL_REMINDER PODCAST 04-10-2024\n" +
        //         "RENEWAL_AMOUNT 1400";
        // Assertions.assertEquals(expected, outputStream.toString().trim());

        //Assertions.assertTrue(true);
    }

}